@host = http://localhost:3000/api/v1
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50Ijp7ImlkIjoiMjRiMjA0OWYtMjEzMC00MTc3LWExOTYtZTQyMDdhZDhkNWI2Iiwicm9sZSI6IkNPQUNIIn0sImlhdCI6MTY1MTAwOTc5MSwiZXhwIjoxNjUxNjE0NTkxfQ.65QNhFI26f4PERJT6WOV11XgUXjKfT9i4lCw1TrMB2U
@id = 24b2049f-2130-4177-a196-e4207ad8d5b6
@coachId = 24b2049f-2130-4177-a196-e4207ad8d5b6
@reviewId = 608f36cc-9afa-4f55-90a5-bd7fb21169ba

// create coach profile
POST {{host}}/coaches
content-type: application/json
Authorization: Bearer {{token}}

{
    "bio": "fitness coach lesgoo"
}
###
// get coach profile
GET {{host}}/coaches/{{coachId}}
Authorization: Bearer {{token}}



###
// update coach profile
PATCH {{host}}/coaches/{{coachId}}
content-type: application/json
Authorization: Bearer {{token}}

{
    "bio":"dsffdsojds dfsofsdopf"
}


###
// post review
POST {{host}}/coaches/{{coachId}}/reviews/
content-type: application/json
Authorization: Bearer {{token}}

{            
    "description":"lorem sadkljferijflksf",       
    "rating":5
}

###
// get reviews
GET {{host}}/coaches/{{coachId}}/reviews
Authorization: Bearer {{token}}

###
// delete review
DELETE  {{host}}/coaches/reviews/{{reviewId}}
Authorization: Bearer {{token}}



###
// update review
PATCH {{host}}/coaches/reviews/{{reviewId}}
content-type: application/json
Authorization: Bearer {{token}}

{
    "rating":4
}


###
// get exercises
GET {{host}}/coaches/{{coachId}}/exercises
Authorization: Bearer {{token}}
###
// get programs
GET {{host}}/coaches/{{coachId}}/programs
Authorization: Bearer {{token}}