@host = http://localhost:3000/api/v1
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50Ijp7ImlkIjoiZDlhNTFkMzUtOTM5My00Mjc3LTljMDAtZjA1NDliM2M1ZjE5Iiwicm9sZSI6IlRSQUlORUUifSwiaWF0IjoxNjQ2MjczNDI5LCJleHAiOjE2NDY4NzgyMjl9.eVBDahpyO84qseuJkrVOjLq3tfMnRdZWfwHBv2HVPjg
@id = d9a51d35-9393-4277-9c00-f0549b3c5f19
@coachId = c0ce7b2b-38cb-432a-a85f-271476c3833f
@reviewId = 608f36cc-9afa-4f55-90a5-bd7fb21169ba

// create coach profile
POST {{host}}/coaches
content-type: application/json
Authorization: {{token}}

{
    "bio": "fitness coach lesgoo"
}
###
// get coach profile
GET {{host}}/coaches/{{coachId}}
Authorization: {{token}}



###
// update coach profile
PATCH {{host}}/coaches/{{coachId}}
content-type: application/json
Authorization: {{token}}

{
    "bio":"dsffdsojds dfsofsdopf"
}


###
// post review
POST {{host}}/coaches/{{coachId}}/reviews/
content-type: application/json
Authorization: {{token}}

{            
    "description":"lorem sadkljferijflksf",       
    "rating":5
}

###
// get reviews
GET {{host}}/coaches/{{coachId}}/reviews
Authorization: {{token}}

###
// delete review
DELETE  {{host}}/coaches/reviews/{{reviewId}}
Authorization: {{token}}



###
// update review
PATCH {{host}}/coaches/reviews/{{reviewId}}
content-type: application/json
Authorization: {{token}}

{
    "rating":4
}


###
// get exercises
GET {{host}}/coaches/{{coachId}}/exercises
Authorization: {{token}}