@host = http://localhost:3000/api/v1
@token =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50Ijp7ImlkIjoiYzBjZTdiMmItMzhjYi00MzJhLWE4NWYtMjcxNDc2YzM4MzNmIiwicm9sZSI6IkNPQUNIIn0sImlhdCI6MTY0NjQxMTAxMCwiZXhwIjoxNjQ3MDE1ODEwfQ.LvlVlMdDTf0W3SzgOM6XdMGq-S-RHmpnGZF62f4NbMM
@exerciseId = 772f5035-d3d5-4757-801b-7b4c6ef12bdc

@accountId =c0ce7b2b-38cb-432a-a85f-271476c3833f

###
// post exercise
POST {{host}}/exercises/
content-type: application/json
Authorization: {{token}}

{
    "title":"pushups",              
    "description":"lorem sadkljferijflksf",       
    "videoUrl":"test",          
    "imgUrl":"test",         
    "activeMuscle":"Shoulders"
}

###
// get exercise
GET {{host}}/exercises/{{exerciseId}}
Authorization: {{token}}

###
// delete exercise
DELETE  {{host}}/exercises/{{exerciseId}}
Authorization: {{token}}



###
// update exercise
PATCH {{host}}/exercises/{{exerciseId}}
content-type: application/json
Authorization: {{token}}

{
    "title":"pullups",
    "imgUrl":"test"
}