@host = http://localhost:3000/api/v1
@token =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50Ijp7ImlkIjoiMjRiMjA0OWYtMjEzMC00MTc3LWExOTYtZTQyMDdhZDhkNWI2Iiwicm9sZSI6IkNPQUNIIn0sImlhdCI6MTY1MTAwOTc5MSwiZXhwIjoxNjUxNjE0NTkxfQ.65QNhFI26f4PERJT6WOV11XgUXjKfT9i4lCw1TrMB2U
@programId =337f5485-35d9-48b2-b3e9-7d6b3c9fbf78
@dayId=1aac8c50-3d3e-4a51-b50c-cc181d675cbd
###
// post program
POST {{host}}/programs/
content-type: application/json
Authorization: Bearer {{token}}

{
   "title":"Test Program",
   "description":"lorem sadkljferijflksf",
   "imgUrl":"test",
   "price":1999,
   "weeks":[
      {
         "order":1,
         "days":[
            {
               "order":1,
               "exercises":[
                  {
                     "order":1,
                     "reps":5,
                     "sets":10,
                     "exerciseId":"4e8f3bab-56dc-47db-b5e6-c6656d9a7e4a"
                  }
               ]
            },
            {
               "order":2,
               "exercises":[
                  {
                     "order":1,
                     "reps":5,
                     "sets":10,
                     "exerciseId":"4e8f3bab-56dc-47db-b5e6-c6656d9a7e4a"
                  }
               ]
            }
         ]
      },
      {
         "order":2,
         "days":[
            {
               "order":1,
               "exercises":[
                  {
                     "order":1,
                     "reps":5,
                     "sets":10,
                     "exerciseId":"4e8f3bab-56dc-47db-b5e6-c6656d9a7e4a"
                  }
               ]
            },
            {
               "order":2,
               "exercises":[
                  {
                     "order":1,
                     "reps":5,
                     "sets":10,
                     "exerciseId":"4e8f3bab-56dc-47db-b5e6-c6656d9a7e4a"
                  }
               ]
            }
         ]
      }
   ]
}
###
// update program
PATCH {{host}}/programs/{{programId}}
content-type: application/json
Authorization: Bearer {{token}}

{
    "title":"Test Program update",              
    "description":"lorem sadkljferijflksf",                
    "imgUrl":"test",         
    "weeks":[
        {
            "order":4,
            "days":[
                {
                    "order":3,
                    "exercises":[
                        {
                            "order":1,
                            "reps":5,
                            "sets":10,
                            "exerciseId":"5ad9d9f0-3214-4018-924d-d4087773eb45"
                        }
                    ]
                },
                {
                    "order":1,
                    "exercises":[
                        {
                            "order":1,
                            "reps":5,
                            "sets":10,
                            "exerciseId":"5ad9d9f0-3214-4018-924d-d4087773eb45"
                        }
                    ]
                },
                {
                    "order":4,
                    "exercises":[
                        {
                            "order":2,
                            "reps":5,
                            "sets":10,
                            "exerciseId":"5ad9d9f0-3214-4018-924d-d4087773eb45"
                        }
                    ]
                }

            ]
        },
        {
            "order":2,
            "days":[
                {
                    "order":1,
                    "exercises":[
                        {
                            "order":1,
                            "reps":5,
                            "sets":10,
                            "exerciseId":"5ad9d9f0-3214-4018-924d-d4087773eb45"
                        }
                    ]
                },
                {
                    "order":2,
                    "exercises":[
                        {
                            "order":1,
                            "reps":5,
                            "sets":10,
                            "exerciseId":"5ad9d9f0-3214-4018-924d-d4087773eb45"
                        }
                    ]
                }

            ]
        }
    ]
}


###
// get program
GET {{host}}/programs/{{programId}}
content-type: application/json
Authorization: Bearer {{token}}
###
// get program day exercises
GET {{host}}/programs/{{programId}}/days/{{dayId}}/exercises
content-type: application/json
Authorization: Bearer {{token}}
###
// delete program
DELETE {{host}}/programs/{{programId}}
content-type: application/json
Authorization: Bearer {{token}}