@host = http://localhost:3000/api/v1
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50Ijp7ImlkIjoiZGQ3ZTlmOTctOTI0ZS00NDI5LWIzMzktZDIwNGRhOTIzNWRiIiwicm9sZSI6IlRSQUlORUUifSwiaWF0IjoxNjQ1ODg2NTkwfQ.zbpeKOuycJOF7v5-bEJ3Xm6lm6GNJyknPeMfPbCnaVE
@id = e4191bd3-67e3-4ae2-b94c-12f7140d218c

// create trainee profile
POST {{host}}/trainees
content-type: application/json
Authorization: {{token}}

{
    "age":18,
    "weight":60,
    "height":167,
    "gender":"MALE",
    "goal":"FIT"
}
###
// get trainee profile
GET {{host}}/trainees/{{id}}
Authorization: {{token}}



###
// update trainee profile
PATCH {{host}}/trainees/{{id}}
content-type: application/json
Authorization: {{token}}

{
    "weight":66
}