name: CD

on:
  push:
    branches: [main]

jobs:
  Continous_Deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Restart backend
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_SSH_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: cd "FitClub-backend/" && git pull && npm i && npm run build && pm2 start
      - uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
